import { Metadata } from "next";
import ResetForm from "../_components/reset-form";
export const metadata: Metadata = {
    title: "Reset password",
    description: "Generated by create next app",
  };
const ResetPage = () => {
    return <div><ResetForm/></div>;
}
 
export default ResetPage;