import { Metadata } from "next";
import NewPasswordForm from "../_components/new-password-form";
export const metadata: Metadata = {
    title: "Reset password",
    description: "Generated by create next app",
  };
const NewPasswordPage = () => {
    return <div><NewPasswordForm/></div>;
}
 
export default NewPasswordPage;