import { Metadata } from "next";
import RegisterForm from "../_components/register-form";
export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};
const Register = () => {
  return (
    <div>
      <RegisterForm />
    </div>
  );
};

export default Register;
