import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Active mail",
    description: "Generated by create next app",
};

import ActiveMailForm from "../_components/form-active-mail";

const ActiveMail = () => {
    return <div><ActiveMailForm/></div>;
}
 
export default ActiveMail;