import LoginForm from "../_components/login-form";
import LoginFormServerAction from "../_components/login-form-server";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login",
    description: "Generated by create next app",
  };
const Login = () => {
    return ( <LoginForm/>);
    // return <LoginFormServerAction/>
}
 
export default Login;