import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { dir } from 'i18next'
import { languages } from '@/i18n/setting'
import { Footer } from "@/components/ui/footer/page";
import { useTranslation } from "@/i18n";
import Navbar from "@/components/ui/navbar/page";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}
const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode,
  params:{lng: any}
}) {
  const session = await auth();
  const { t } = await useTranslation(lng);
  return (
    <SessionProvider session={session}>
      <html lang={lng} dir={dir(lng)}>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Navbar lng={lng}/>
          {children}
          <Footer lng={lng}/>
        </body>
      </html>
    </SessionProvider>
  );
}


