import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { dir } from "i18next";
import { languages } from "@/i18n/setting";
import { Footer } from "@/components/ui/footer/page";
import AppProvider from "@/contexts/AppContext";
import Header from "@/components/ui/header/page";
import { ThemeProvider } from "@/components/theme-provider";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: any };
}) {
  const session = await auth();
  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider language={lng}>
              <Header lng={lng}/>
              <div>
              {children}
              </div>
              <Footer lng={lng} />
            </AppProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
